import { query, withTenant } from "@/lib/db"
import { currentContext } from "@/lib/session"
import { mayManageTenant } from "@/lib/rbac"
import { updateClientSettings } from "./actions"

type Settings = {name:string;slug:string;status:string;timezone:string;currency:string;target_acos_default:number;max_changes_per_day:number;profile_id:string|null;country_code:string|null;connection_status:string|null}

export default async function ClientSettingsPage() {
	const actor = await currentContext()
	const settings = await withTenant(actor.tenantId, async c => (await query<Settings>(c, `select t.name,t.slug,t.status,s.timezone,s.currency,s.target_acos_default,s.max_changes_per_day,p.profile_id::text,p.country_code,ac.status connection_status from tenant t join tenant_settings s on s.tenant_id=t.id left join ads_profile p on p.tenant_id=t.id left join amazon_connection ac on ac.id=p.connection_id where t.id=$1 order by p.created_at limit 1`, [actor.tenantId]))[0])
	const editable = mayManageTenant(actor.role)
	return <div className="space-y-6"><div><h1 className="text-lg font-semibold">Client settings</h1><p className="text-sm text-slate-600">Tenant identity and operating defaults are stored per client—not hard-coded in the dashboard.</p></div><form action={updateClientSettings} className="grid max-w-3xl gap-4 rounded border bg-white p-5 md:grid-cols-2"><label className="text-sm font-medium">Client display name<input disabled={!editable} required name="name" defaultValue={settings.name} className="mt-1 w-full rounded border px-3 py-2 disabled:bg-slate-100"/></label><label className="text-sm font-medium">Tenant slug<input disabled={!editable} required name="slug" defaultValue={settings.slug} className="mt-1 w-full rounded border px-3 py-2 font-mono disabled:bg-slate-100"/></label><label className="text-sm font-medium">Reporting timezone<input disabled={!editable} required name="timezone" defaultValue={settings.timezone} className="mt-1 w-full rounded border px-3 py-2 disabled:bg-slate-100"/></label><label className="text-sm font-medium">Target ACOS (%)<input disabled={!editable} required type="number" step="0.01" min="0.01" max="200" name="targetAcos" defaultValue={settings.target_acos_default*100} className="mt-1 w-full rounded border px-3 py-2 disabled:bg-slate-100"/></label><label className="text-sm font-medium">Maximum changes per day<input disabled={!editable} required type="number" min="1" max="500" name="maxChanges" defaultValue={settings.max_changes_per_day} className="mt-1 w-full rounded border px-3 py-2 disabled:bg-slate-100"/></label><div className="rounded bg-slate-50 p-3 text-sm"><b>Amazon Ads profile</b><div className="mt-1 text-slate-600">{settings.profile_id ? `${settings.country_code ?? "Amazon"} profile ${settings.profile_id}` : "Pending profile discovery"}</div><div className="text-xs text-slate-500">Connection: {settings.connection_status ?? "not configured"}. Profile IDs come from Amazon discovery and cannot be manually forged.</div></div>{editable ? <button className="w-fit rounded bg-slate-900 px-4 py-2 text-white">Save client settings</button> : <p className="text-sm tone-warn">Your role has read-only access.</p>}</form><div className="text-xs text-slate-500">Tenant ID: <code>{actor.tenantId}</code> · Currency: {settings.currency} · Status: {settings.status} · Your role: {actor.role}</div></div>
}
