import { query, withTenant } from "@/lib/db"
import { currentContext } from "@/lib/session"
import { SettingsHeading } from "@/components/settings-ui"
import { createProtection, releaseProtection } from "./actions"

type Protection = { id:string; entity_type:string; entity_value:string; product_scope:string; policy:string; duration:string; expires_at:string|null; reason:string; created_at:string; latest_event:string }
export const dynamic = "force-dynamic"

export default async function ProtectionsPage() {
	const actor = await currentContext()
	const rows = await withTenant(actor.tenantId, c => query<Protection>(c, `select p.id,p.entity_type,p.entity_value,p.product_scope,p.policy,p.duration,p.expires_at::text,p.reason,p.created_at::text,(select e.event_type from entity_protection_event e where e.protection_id=p.id and e.tenant_id=p.tenant_id order by e.occurred_at desc,e.id desc limit 1) latest_event from entity_protection p order by p.created_at desc`, []))
	const canManage = actor.role === "owner" || actor.role === "admin"
	return <div className="space-y-6"><SettingsHeading title="Protected entities" description="Prevent automation from silently negating or pausing strategic keywords, customer queries and ASINs."/>
		<div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Safety boundary:</b> allow/protect entries block destructive automated proposals. Deny entries permit a negative recommendation, but live application still requires capability support, human approval, reread, drift checks and audit.</div>
		{canManage && <form action={createProtection} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-medium">Add protection policy</h2><div className="grid gap-3 md:grid-cols-3"><select name="entityType" className="rounded border px-3 py-2"><option value="search_term">Search term</option><option value="keyword">Keyword</option><option value="asin">ASIN</option></select><input required name="entityValue" placeholder="Entity value" className="rounded border px-3 py-2"/><input name="productScope" placeholder="Product scope or *" className="rounded border px-3 py-2"/><select name="policy" className="rounded border px-3 py-2"><option value="protect">Protect</option><option value="allow">Allow list</option><option value="deny">Deny list</option></select><select name="duration" className="rounded border px-3 py-2"><option value="persistent">Persistent</option><option value="temporary">Temporary</option><option value="one_time">One-time</option></select><input type="datetime-local" name="expiresAt" className="rounded border px-3 py-2"/></div><div className="flex gap-3"><input required name="reason" placeholder="Required operator reason" className="min-w-0 flex-1 rounded border px-3 py-2"/><button className="rounded bg-slate-900 px-4 py-2 text-white">Add policy</button></div></form>}
		<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-3">Entity</th><th className="p-3">Policy</th><th className="p-3">Duration</th><th className="p-3">Reason / state</th><th className="p-3">Control</th></tr></thead><tbody>{rows.length ? rows.map(row => { const active = row.latest_event === "created" && (!row.expires_at || new Date(row.expires_at) > new Date()); return <tr key={row.id} className="border-b align-top"><td className="p-3"><b>{row.entity_value}</b><div className="text-xs text-slate-500">{row.entity_type} · {row.product_scope}</div></td><td className="p-3 capitalize">{row.policy}</td><td className="p-3 capitalize">{row.duration.replace("_", " ")}<div className="text-xs text-slate-500">{row.expires_at ?? "No expiry"}</div></td><td className="p-3">{row.reason}<div className={active ? "text-xs tone-good" : "text-xs text-slate-400"}>{active ? "Active" : row.latest_event}</div></td><td className="p-3">{canManage && active ? <form action={releaseProtection} className="flex gap-2"><input type="hidden" name="id" value={row.id}/><input required name="reason" placeholder="Release reason" className="w-36 rounded border px-2 py-1 text-xs"/><button className="rounded border px-2 py-1 text-xs">Return to automation</button></form> : "—"}</td></tr> }) : <tr><td colSpan={5} className="p-8 text-center text-slate-500">No protected entities configured.</td></tr>}</tbody></table></div>
	</div>
}
