import Link from "next/link"
import { withTenant } from "@/lib/db"
import { acosTone, count, money, percent, reportDate, stamp } from "@/lib/format"
import { accountTotals, campaignPerformance, openAlerts, openFindings, productAnalytics, recentPipelineRuns, type CampaignRow, type ProductRow } from "@/lib/queries"
import { ALLOWED_WINDOWS, parseDays, windowHref, type Window } from "@/lib/range"
import { currentTenantId } from "@/lib/session"

export const dynamic = "force-dynamic"

function Kpi({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold tabular-nums">{value}</div>{note && <div className="mt-1 text-xs text-slate-500">{note}</div>}</div> }
function WindowPicker({ days }: { days: Window }) { return <div className="flex gap-1 text-xs">{ALLOWED_WINDOWS.map((d) => <Link key={d} href={windowHref("/", d)} className={d === days ? "rounded bg-slate-900 px-2 py-1 text-white" : "rounded border border-slate-300 px-2 py-1 text-slate-600 hover:bg-slate-100"}>{d}d</Link>)}</div> }
function AcosCell({ row }: { row: CampaignRow }) { const tone = acosTone(row.acos, row.break_even_acos); return <td className={`num px-3 py-2 tone-${tone}`}>{percent(row.acos)}{row.economics_incomplete && <span className="ml-1 text-slate-400" title="No cost data for at least one advertised ASIN">?</span>}</td> }
function ProductAcos({ row }: { row: ProductRow }) { const tone = acosTone(row.tacos, row.break_even_acos); return <td className={`num px-3 py-2 tone-${tone}`}>{percent(row.tacos)}{row.economics_incomplete && <span className="ml-1 text-slate-400" title="Fill sku_cost_ledger to enable product profit rules">?</span>}</td> }
function runTone(status: string): string { if (status === "success") return "tone-good"; if (status === "failed" || status === "partial") return "tone-bad"; if (status === "running") return "tone-warn"; return "tone-unknown" }
function alertTone(severity: string): string { if (severity === "critical") return "border-red-200 bg-red-50 text-red-800"; if (severity === "warning") return "border-amber-200 bg-amber-50 text-amber-800"; return "border-slate-200 bg-slate-50 text-slate-700" }

export default async function CommandCenter({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
	const sp = await searchParams
	const days = parseDays(sp.days)
	const tenantId = currentTenantId()
	const { totals, campaigns, findings, products, runs, alerts } = await withTenant(tenantId, async (c) => ({ totals: await accountTotals(c, days), campaigns: await campaignPerformance(c, days), findings: await openFindings(c, 20), products: await productAnalytics(c, days, 12), runs: await recentPipelineRuns(c, 5), alerts: await openAlerts(c, 3) }))
	if (campaigns.length === 0 && products.length === 0) return <div className="rounded-lg border border-slate-200 bg-white p-8"><h1 className="text-lg font-semibold">No settled performance data yet</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Run Ads/SP-API ingest and dbt build first. The dashboard intentionally avoids fake zeroes when there is no data.</p>{alerts.length > 0 && <div className="mt-6 max-w-2xl space-y-2">{alerts.map((a) => <Link key={a.id} href="/history" className={`block rounded border px-3 py-2 text-sm ${alertTone(a.severity)}`}><span className="font-medium">{a.severity}: {a.title}</span><span className="ml-2 text-xs">{stamp(a.created_at)}</span></Link>)}</div>}{runs.length > 0 && <div className="mt-6 max-w-2xl"><h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Recent pipeline runs</h2><div className="mt-2 space-y-2">{runs.map((r, i) => <div key={`${r.dataset}-${r.started_at}-${i}`} className="rounded border border-slate-100 bg-slate-50 px-3 py-2 text-sm"><div className="flex justify-between gap-3"><span className="font-medium">{r.dataset}</span><span className={runTone(r.status)}>{r.status}</span></div><div className="text-xs text-slate-500">{stamp(r.started_at)}{r.finished_at ? ` → ${stamp(r.finished_at)}` : ""} · {r.rows_loaded ?? 0} rows</div></div>)}</div><Link href="/history" className="mt-3 inline-block text-sm text-blue-700 hover:underline">Open run history →</Link></div>}</div>
	return <div className="space-y-8">{alerts.length > 0 && <section className="space-y-2">{alerts.map((a) => <Link key={a.id} href="/history" className={`block rounded-lg border px-4 py-3 text-sm ${alertTone(a.severity)}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold">{a.severity}: {a.title}</span><span className="text-xs">{stamp(a.created_at)}</span></div><div className="text-xs opacity-80">{a.kind}{a.entity_ref ? ` · ${a.entity_ref}` : ""}</div></Link>)}</section>}<section><div className="mb-3 flex flex-wrap items-baseline justify-between gap-3"><h1 className="text-lg font-semibold">PPC Command Center</h1><div className="flex items-center gap-3"><span className="text-xs text-slate-500">last {days} settled days{totals?.data_through && ` · through ${reportDate(totals.data_through)}`}</span><WindowPicker days={days} /></div></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Kpi label="Ad spend" value={money(totals?.cost ?? 0)} /><Kpi label="Ad sales" value={money(totals?.sales ?? 0)} /><Kpi label="ACOS" value={percent(totals?.acos ?? null)} note="spend ÷ ad sales" /><Kpi label="Campaigns" value={String(totals?.campaigns ?? 0)} note={`${count(totals?.orders ?? 0)} orders`} /></div></section>
	<section className="rounded-lg border border-slate-200 bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Recent pipeline runs</h2><Link href="/history" className="text-sm text-blue-700 hover:underline">Full history →</Link></div>{runs.length === 0 ? <p className="text-sm text-slate-500">No pipeline runs yet.</p> : <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5">{runs.map((r, i) => <div key={`${r.dataset}-${r.started_at}-${i}`} className="rounded border border-slate-100 p-2 text-sm"><div className="truncate font-medium" title={r.dataset}>{r.dataset}</div><div className={`text-xs ${runTone(r.status)}`}>{r.status}</div><div className="text-xs text-slate-500">{stamp(r.started_at)}</div><div className="text-xs text-slate-500">{r.rows_loaded ?? 0} rows</div></div>)}</div>}</section>
	<section><h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Product analytics</h2>{products.length === 0 ? <p className="text-sm text-slate-500">No product-level Sales & Traffic rows yet.</p> : <table className="w-full border-collapse bg-white text-sm"><thead><tr className="border-b border-slate-300 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-2">Product</th><th className="px-3 py-2 text-right">Units</th><th className="px-3 py-2 text-right">Total sales</th><th className="px-3 py-2 text-right">Ad spend</th><th className="px-3 py-2 text-right">TACoS</th><th className="px-3 py-2 text-right">Break-even</th><th className="px-3 py-2 text-right">Est. gross profit</th></tr></thead><tbody>{products.map((row) => <tr key={row.asin} className="border-b border-slate-100"><td className="px-3 py-2"><div className="font-medium">{row.asin}</div><div className="text-xs text-slate-500">{row.sku ?? "no SKU"}</div></td><td className="num px-3 py-2">{count(row.units)}</td><td className="num px-3 py-2">{money(row.total_sales)}</td><td className="num px-3 py-2">{money(row.ad_spend)}</td><ProductAcos row={row} /><td className="num px-3 py-2 text-slate-500">{percent(row.break_even_acos)}</td><td className="num px-3 py-2">{row.gross_profit_est === null ? "—" : money(row.gross_profit_est)}</td></tr>)}</tbody></table>}<p className="mt-2 text-xs text-slate-500">TACoS is ad spend ÷ total product sales. Estimated gross profit uses SKU economics contribution margin minus ad spend.</p></section>
	<section><table className="w-full border-collapse bg-white text-sm"><thead><tr className="border-b border-slate-300 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-2">Campaign</th><th className="px-3 py-2 text-right">Spend</th><th className="px-3 py-2 text-right">Sales</th><th className="px-3 py-2 text-right">ACOS</th><th className="px-3 py-2 text-right">Break-even</th><th className="px-3 py-2 text-right">CTR</th><th className="px-3 py-2 text-right">CVR</th><th className="px-3 py-2 text-right">CPC</th><th className="px-3 py-2 text-right">Budget used</th></tr></thead><tbody>{campaigns.map((row) => <tr key={row.campaign_id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-3 py-2"><Link href={`/campaigns/${encodeURIComponent(row.campaign_id)}?days=${days}`} className="font-medium text-blue-700 hover:underline">{row.campaign_name}</Link><div className="text-xs text-slate-500">{row.campaign_status ?? "unknown"}{row.targeting_type ? ` · ${row.targeting_type}` : ""}</div></td><td className="num px-3 py-2">{money(row.cost)}</td><td className="num px-3 py-2">{money(row.sales)}</td><AcosCell row={row} /><td className="num px-3 py-2 text-slate-500">{row.break_even_acos === null ? "no cost data" : percent(row.break_even_acos)}</td><td className="num px-3 py-2">{percent(row.ctr, 2)}</td><td className="num px-3 py-2">{percent(row.cvr)}</td><td className="num px-3 py-2">{money(row.cpc)}</td><td className="num px-3 py-2">{percent(row.budget_utilisation, 0)}</td></tr>)}</tbody></table></section>
	<section><h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Findings ({findings.length})</h2>{findings.length === 0 ? <p className="text-sm text-slate-500">Nothing flagged.</p> : <ul className="space-y-2">{findings.map((f) => <li key={f.id} className="rounded border border-amber-200 bg-amber-50 px-3 py-2 text-sm"><span className="font-medium">{f.rule_name ?? f.rule_code}</span><span className="text-slate-500"> · {f.entity_type} {f.entity_id}</span><div className="text-slate-700">{f.reason_text}</div></li>)}</ul>}<div className="mt-4 flex gap-4 text-sm"><Link href="/approvals" className="text-blue-700 hover:underline">Approval queue →</Link><Link href={`/search-terms?days=${days}`} className="text-blue-700 hover:underline">Search terms →</Link><Link href={`/history?days=${days}`} className="text-blue-700 hover:underline">Decision history →</Link></div></section></div>
}
