import type { PoolClient } from "pg"
import { mart, query } from "./db"

export type CampaignRow = { campaign_id: string; campaign_name: string; campaign_status: string | null; targeting_type: string | null; budget_amount: number | null; impressions: number; clicks: number; cost: number; orders: number; sales: number; acos: number | null; roas: number | null; ctr: number | null; cvr: number | null; cpc: number | null; break_even_acos: number | null; economics_incomplete: boolean; budget_utilisation: number | null; days: number }
export async function campaignPerformance(client: PoolClient, days = 30): Promise<CampaignRow[]> { return query<CampaignRow>(client, `with window_rows as (select * from ${mart("mart_ppc_campaign_daily")} where is_settled and report_date >= current_date - ($1::int || ' days')::interval), latest_budget as (select distinct on (campaign_id) campaign_id, budget_amount, campaign_status, campaign_name, targeting_type from window_rows order by campaign_id, report_date desc) select w.campaign_id, b.campaign_name, b.campaign_status, b.targeting_type, b.budget_amount, sum(w.impressions) as impressions, sum(w.clicks) as clicks, sum(w.cost) as cost, sum(w.attributed_orders_7d) as orders, sum(w.attributed_sales_7d) as sales, case when sum(w.attributed_sales_7d) > 0 then sum(w.cost) / sum(w.attributed_sales_7d) end as acos, case when sum(w.cost) > 0 then sum(w.attributed_sales_7d) / sum(w.cost) end as roas, case when sum(w.impressions) > 0 then sum(w.clicks)::numeric / sum(w.impressions) end as ctr, case when sum(w.clicks) > 0 then sum(w.attributed_orders_7d)::numeric / sum(w.clicks) end as cvr, case when sum(w.clicks) > 0 then sum(w.cost) / sum(w.clicks) end as cpc, min(w.break_even_acos) as break_even_acos, bool_or(w.economics_incomplete) as economics_incomplete, case when sum(w.budget_amount) > 0 then sum(w.cost) / sum(w.budget_amount) end as budget_utilisation, count(*) as days from window_rows w join latest_budget b using (campaign_id) group by w.campaign_id, b.campaign_name, b.campaign_status, b.targeting_type, b.budget_amount order by sum(w.cost) desc`, [days]) }

export type AccountTotals = { cost: number; sales: number; orders: number; clicks: number; impressions: number; acos: number | null; campaigns: number; data_through: string | null }
export async function accountTotals(client: PoolClient, days = 30): Promise<AccountTotals | null> { const rows = await query<AccountTotals>(client, `select coalesce(sum(cost), 0) as cost, coalesce(sum(attributed_sales_7d), 0) as sales, coalesce(sum(attributed_orders_7d), 0) as orders, coalesce(sum(clicks), 0) as clicks, coalesce(sum(impressions), 0) as impressions, case when sum(attributed_sales_7d) > 0 then sum(cost) / sum(attributed_sales_7d) end as acos, count(distinct campaign_id) as campaigns, max(report_date)::text as data_through from ${mart("mart_ppc_campaign_daily")} where is_settled and report_date >= current_date - ($1::int || ' days')::interval`, [days]); return rows[0] ?? null }

export type ProductRow = { asin: string; sku: string | null; units: number; total_sales: number; ad_spend: number; ad_sales: number; tacos: number | null; acos: number | null; contribution_margin_pct: number | null; break_even_acos: number | null; economics_incomplete: boolean; gross_profit_est: number | null }
export async function productAnalytics(client: PoolClient, _days = 30, limit = 20): Promise<ProductRow[]> { return query<ProductRow>(client, `select asin, sku, units_30d as units, sales_30d as total_sales, ad_spend_30d as ad_spend, ad_sales_30d as ad_sales, tacos, case when ad_sales_30d > 0 then ad_spend_30d / ad_sales_30d end as acos, contribution_margin_pct, break_even_acos, economics_incomplete, case when contribution_margin_pct is not null then sales_30d * contribution_margin_pct - ad_spend_30d end as gross_profit_est from ${mart("mart_product_opportunity")} order by sales_30d desc, ad_spend_30d desc limit $1`, [limit]) }

export type PendingAction = { id: string; entity_type: string; entity_id: string; action_type: string; before_value: unknown; after_value: unknown; reason_text: string | null; clamped: boolean; clamp_note: string | null; requested_at: string; expires_at: string; rule_code: string | null; rule_name: string | null }
export async function pendingActions(client: PoolClient, limit = 100): Promise<PendingAction[]> { return query<PendingAction>(client, `select a.id, a.entity_type, a.entity_id, a.action_type, a.before_value, a.after_value, a.reason_text, a.clamped, a.clamp_note, a.requested_at, a.expires_at, r.code as rule_code, r.name as rule_name from action a left join rule r on r.id = a.rule_id where a.status = 'pending' and a.action_type <> 'flag' and a.expires_at > now() order by a.requested_at asc limit $1`, [limit]) }
export type Finding = { id: string; entity_type: string; entity_id: string; reason_text: string | null; requested_at: string; rule_code: string | null; rule_name: string | null }
export async function openFindings(client: PoolClient, limit = 100): Promise<Finding[]> { return query<Finding>(client, `select a.id, a.entity_type, a.entity_id, a.reason_text, a.requested_at, r.code as rule_code, r.name as rule_name from action a left join rule r on r.id = a.rule_id where a.status = 'pending' and a.action_type = 'flag' order by a.requested_at desc limit $1`, [limit]) }
export type Freshness = { dataset: string; last_success: string | null; last_status: string | null; hours_old: number | null }
export async function dataFreshness(client: PoolClient): Promise<Freshness[]> { return query<Freshness>(client, `select distinct on (dataset) dataset, finished_at::text as last_success, status as last_status, round(extract(epoch from (now() - finished_at)) / 3600.0, 1) as hours_old from pipeline_run order by dataset, started_at desc`) }
export type AutomationState = { automation_enabled: boolean; dry_run: boolean; target_acos_default: number | null; max_changes_per_day: number | null; currency: string | null }
export async function automationState(client: PoolClient): Promise<AutomationState | null> { const rows = await query<AutomationState>(client, `select automation_enabled, dry_run, target_acos_default, max_changes_per_day, currency from tenant_settings limit 1`); return rows[0] ?? null }
export type OpenAlert = { id: string; kind: string; severity: string; title: string; entity_ref: string | null; created_at: string; detail: unknown }
export async function openAlerts(client: PoolClient, limit = 20): Promise<OpenAlert[]> { return query<OpenAlert>(client, `select id::text, kind, severity, title, entity_ref, created_at::text, detail from alert where resolved_at is null order by case severity when 'critical' then 0 when 'warning' then 1 else 2 end, created_at desc limit $1`, [limit]) }

export type ProductOpportunity = { asin: string; sku: string | null; title: string | null; brand: string | null; buy_box_price: number | null; sales_rank: number | null; review_count: number | null; rating: number | null; offer_count: number | null; units_30d: number; sales_30d: number; contribution_margin_pct: number | null; break_even_acos: number | null; economics_incomplete: boolean; opportunity_score: number; keepa_captured_at: string | null }
export async function productOpportunities(client: PoolClient, minScore = 0, limit = 100): Promise<ProductOpportunity[]> { return query<ProductOpportunity>(client, `select asin, sku, title, brand, buy_box_price, sales_rank, review_count, rating, offer_count, units_30d, sales_30d, contribution_margin_pct, break_even_acos, economics_incomplete, opportunity_score, keepa_captured_at::text from ${mart("mart_product_opportunity")} where opportunity_score >= $1 order by opportunity_score desc, sales_30d desc limit $2`, [minScore, limit]) }

export type SqpOpportunity = { asin: string; search_query: string; query_volume_30d: number; query_ctr: number | null; query_cvr: number | null; ad_spend_30d: number; ads_acos: number | null; exists_as_exact: boolean; economics_incomplete: boolean; sqp_opportunity_score: number; suggested_action: string }
export async function sqpOpportunities(client: PoolClient, action = "all", limit = 100): Promise<SqpOpportunity[]> { return query<SqpOpportunity>(client, `select asin, search_query, query_volume_30d, query_ctr, query_cvr, ad_spend_30d, ads_acos, exists_as_exact, economics_incomplete, sqp_opportunity_score, suggested_action from ${mart("mart_sqp_opportunity")} where ($1 = 'all' or suggested_action = $1) order by sqp_opportunity_score desc, query_volume_30d desc limit $2`, [action, limit]) }

export type SkuEconomics = { sku: string; asin: string | null; currency: string; avg_price: number | null; cogs: number; freight_in: number; fba_fee: number; storage_est: number; total_unit_cost: number | null; contribution_margin: number | null; contribution_margin_pct: number | null; break_even_acos: number | null; economics_incomplete: boolean }
export async function skuEconomics(client: PoolClient, limit = 200): Promise<SkuEconomics[]> { return query<SkuEconomics>(client, `select sku, asin, currency, avg_price, cogs, freight_in, fba_fee, storage_est, total_unit_cost, contribution_margin, contribution_margin_pct, break_even_acos, economics_incomplete from ${mart("mart_sku_economics")} order by economics_incomplete desc, sku limit $1`, [limit]) }
export type PipelineRunSummary = { dataset: string; status: string; started_at: string; finished_at: string | null; rows_loaded: number | null; error: string | null }
export async function recentPipelineRuns(client: PoolClient, limit = 20): Promise<PipelineRunSummary[]> { return query<PipelineRunSummary>(client, `select dataset, status, started_at::text, finished_at::text, rows_loaded, error from pipeline_run order by started_at desc limit $1`, [limit]) }
