import { query, withTenant } from "@/lib/db"
import { currentContext } from "@/lib/session"
import { mayManageMembers } from "@/lib/rbac"
import { addMember, updateMemberRole } from "./actions"

export default async function MembersPage() {
	const actor = await currentContext()
	const members = await withTenant(actor.tenantId, c => query<{user_id:string;name:string;email:string;role:string;created_at:string}>(c, `select m.user_id,u.name,u.email,m.role,m.created_at::text from tenant_member m join auth.auth_user u on u.id=m.user_id where m.tenant_id=$1 order by case m.role when 'owner' then 0 when 'admin' then 1 else 2 end,u.name`, [actor.tenantId]))
	const canManage = mayManageMembers(actor.role)
	return <div className="space-y-6"><div><h1 className="text-lg font-semibold">Team & roles</h1><p className="text-sm text-slate-600">One client tenant, one owner. Owners assign admins or users; admins may add and manage users.</p></div>{canManage && <form action={addMember} className="grid gap-3 rounded border bg-white p-4 md:grid-cols-4"><input required name="name" placeholder="Client user name" className="rounded border px-3 py-2"/><input required type="email" name="email" placeholder="Email" className="rounded border px-3 py-2"/><input required minLength={12} type="password" name="password" placeholder="Temporary password (12+)" className="rounded border px-3 py-2"/><div className="flex gap-2"><select name="role" className="min-w-0 flex-1 rounded border px-2">{actor.role === "owner" && <option value="admin">Admin</option>}<option value="user">User</option></select><button className="rounded bg-slate-900 px-3 text-white">Add</button></div></form>}<div className="overflow-x-auto rounded border bg-white"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-3">Member</th><th className="p-3">Role</th><th className="p-3">Access</th></tr></thead><tbody>{members.map(m => <tr className="border-b" key={m.user_id}><td className="p-3"><b>{m.name}</b><div className="text-xs text-slate-500">{m.email}</div></td><td className="p-3">{canManage && m.role !== "owner" && !(actor.role === "admin" && m.role !== "user") ? <form action={updateMemberRole} className="flex gap-2"><input type="hidden" name="userId" value={m.user_id}/><select name="role" defaultValue={m.role} className="rounded border px-2 py-1">{actor.role === "owner" && <option value="admin">Admin</option>}<option value="user">User</option></select><button className="rounded border px-2 py-1">Save</button></form> : <span className="capitalize">{m.role}</span>}</td><td className="p-3 text-slate-600">{m.role === "owner" ? "Full tenant control" : m.role === "admin" ? "Team + approvals" : "Read-only dashboard"}</td></tr>)}</tbody></table></div></div>
}
