import { isSensitiveScope } from "@/lib/api-scopes"
import { SettingsCard, SettingsHeading, StatusPill } from "@/components/settings-ui"
import { query, withTenant } from "@/lib/db"
import { stamp } from "@/lib/format"
import { mayManageTenant } from "@/lib/rbac"
import { currentContext } from "@/lib/session"
import { revokeApiKey } from "./actions"
import { CreateKeyForm } from "./create-key-form"

type ApiKey = { id:string; name:string; key_prefix:string; scopes:string[]; created_at:string; last_used_at:string|null; revoked_at:string|null }
export default async function ApiKeysPage(){const actor=await currentContext(); const canManage=mayManageTenant(actor.role); const keys=await withTenant(actor.tenantId,c=>query<ApiKey>(c,"select id::text,name,key_prefix,scopes,created_at::text,last_used_at::text,revoked_at::text from tenant_api_key where tenant_id=$1 order by created_at desc",[actor.tenantId])); const sensitiveActive=keys.some(k=>!k.revoked_at && k.scopes.some(isSensitiveScope)); return <div className="space-y-6"><SettingsHeading title="API keys" description="Tenant-scoped keys for programmatic clients. Provider credentials and Amazon tokens are never exposed."/><SettingsCard title="Platform API keys" aside={<StatusPill ready={keys.some(k=>!k.revoked_at)}>{keys.some(k=>!k.revoked_at)?"Enabled":"No active keys"}</StatusPill>}><p className="text-sm text-slate-600">Use platform keys for programmatic clients after the API boundary is stable. Read is safe by default; approval/write scopes are sensitive and stay route-gated by RBAC, idempotency and audit rules.</p>{sensitiveActive && <div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><b>Sensitive API scopes are active.</b> Review clients regularly and revoke keys that no longer need approval/write capability.</div>}<div className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">Amazon refresh tokens use the encrypted vault. AI and email provider keys must be supplied through the deployment secret manager.</div></SettingsCard>{canManage && <CreateKeyForm/>}<div className="overflow-x-auto rounded border bg-white"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-3">Name</th><th className="p-3">Prefix</th><th className="p-3">Scopes</th><th className="p-3">Created</th><th className="p-3">Last used</th><th className="p-3">Status</th></tr></thead><tbody>{keys.length?keys.map(k=><tr key={k.id} className="border-b"><td className="p-3 font-medium">{k.name}</td><td className="p-3 font-mono text-xs">{k.key_prefix}…</td><td className="p-3">{k.scopes.map(s=><span key={s} className={isSensitiveScope(s)?"mr-1 rounded bg-red-100 px-2 py-0.5 text-xs text-red-800":"mr-1 rounded bg-slate-100 px-2 py-0.5 text-xs text-slate-700"}>{s}</span>)}</td><td className="p-3 text-slate-500">{stamp(k.created_at)}</td><td className="p-3 text-slate-500">{stamp(k.last_used_at)}</td><td className="p-3">{k.revoked_at?<span className="tone-unknown">revoked</span>:canManage?<form action={revokeApiKey}><input type="hidden" name="id" value={k.id}/><button className="rounded border px-2 py-1 text-xs text-red-700">Revoke</button></form>:<span className="tone-good">active</span>}</td></tr>):<tr><td colSpan={6} className="p-8 text-center text-slate-500">No platform API keys yet.</td></tr>}</tbody></table></div></div>}
