-- down/0006_diagnostic_actions.sql
-- Reverses 0006: removes the 'flag' action type.
--
-- This down file DELETES existing flag rows, which is the only destructive
-- down file in the repo. That is deliberate and safe for one specific reason:
-- every flag in `action` was written from a `rule_evaluation` row, and that row
-- keeps the full metrics_snapshot, reason_text and rule_id. The finding is not
-- lost by dropping the queue entry -- it can be regenerated by re-running the
-- engine over the same data_through date.
--
-- The alternative (leave the rows, restore the narrow CHECK) does not work:
-- adding a CHECK that existing rows violate fails, so the rollback would abort
-- halfway with the constraint gone and no replacement. Failing at the end of a
-- rollback is worse than a documented delete.

drop index if exists idx_action_tenant_flags_open;

alter table action drop constraint if exists action_flag_is_never_applied;

delete from action where action_type = 'flag';

alter table action drop constraint if exists action_action_type_check;

alter table action
  add constraint action_action_type_check
  check (action_type in ('set_bid','set_budget','pause','enable',
                         'add_negative_exact','add_negative_phrase',
                         'create_keyword','set_placement_modifier'));
