import { COPILOT_QUESTIONS } from "@/lib/copilot-benchmarks"
import { CopilotForm } from "./copilot-form"

export const dynamic = "force-dynamic"

const refusals = ["Amazon refresh tokens and encrypted secrets", "Copilot audit trail raw reads", "User identity and membership dumps", "Direct writes or multi-statement SQL", "Unfiltered marts without tenant-safe views", "Sleep/timeout/comment-smuggling SQL"]

export default function CopilotPage() {
	return <div className="space-y-5"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">System Copilot</p><h1 className="mt-1 text-xl font-semibold text-slate-950">Ask account questions safely</h1><p className="mt-2 max-w-3xl text-sm text-slate-700">The copilot route is tenant-authenticated and now builds a validated no-write runner payload. Python runner execution remains the next service-deploy step; the web boundary already preserves tenant, tier, source and confirmation requirements.</p></div><CopilotForm/><section className="rounded-lg border bg-white p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="font-medium">Supported benchmark questions</h2><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">{COPILOT_QUESTIONS.length} tested prompts</span></div><div className="grid gap-3 md:grid-cols-2">{COPILOT_QUESTIONS.map(q => <article key={q.key} className="rounded border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium uppercase tracking-wide text-slate-500">{q.intent}</span><span className={q.tier === "T2" ? "rounded bg-amber-100 px-2 py-0.5 text-xs text-amber-800" : "rounded bg-green-100 px-2 py-0.5 text-xs text-green-800"}>{q.tier}</span></div><p className="mt-2 text-sm font-medium text-slate-900">{q.question}</p><p className="mt-1 text-sm text-slate-600">{q.questionUr}</p></article>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border bg-white p-4"><h2 className="font-medium">Runner contract</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600"><li>Every prompt carries tenant_id, tier, source and no_write=true.</li><li>T2/write-like prompts require confirmation.</li><li>No route here writes to Amazon or creates an action directly.</li><li>Backend runner keeps read-only role, set_tenant, row caps and auditing.</li></ul></section><section className="rounded-lg border bg-white p-4"><h2 className="font-medium">Must refuse</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-600">{refusals.map(item => <li key={item}>{item}</li>)}</ul></section></div></div>
}
