import Link from "next/link"
import { headers } from "next/headers"
import { auth, authPool } from "@/lib/auth"
import { portfolioSummary, type AccountSummary, type Availability } from "@/lib/portfolio"
import { PortfolioOpenAccount } from "@/components/portfolio-open-account"

export const dynamic = "force-dynamic"

type Workspace = { workspace_id: string; name: string; role: string; can_view_portfolio: boolean; can_operate_tenants: boolean; portfolio_enabled: boolean; cross_account_summary_enabled: boolean; portfolio_alerts_enabled: boolean }
type Params = { workspaceId?: string; q?: string; state?: Availability | "ALL"; sort?: "attention" | "name" | "spend" | "sales"; page?: string; pageSize?: string }

function money(value: number | null, currency: string | null) {
	if (value == null || !currency) return "—"
	try { return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 0 }).format(value) } catch { return `${value.toFixed(2)} ${currency}` }
}
function percent(value: number | null) { return value == null ? "—" : new Intl.NumberFormat("en", { style: "percent", maximumFractionDigits: 1 }).format(value) }
function stateTone(state: Availability) { return state === "AVAILABLE" ? "bg-emerald-50 text-emerald-700" : state === "STALE" ? "bg-amber-50 text-amber-800" : state === "NO_DATA" ? "bg-slate-100 text-slate-600" : "bg-red-50 text-red-700" }
function severityTone(severity: string) { return severity === "CRITICAL" ? "border-red-200 bg-red-50 text-red-800" : severity === "HIGH" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-slate-200 bg-slate-50 text-slate-700" }
function href(workspaceId: string, params: Params, changes: Record<string, string | number>) { const q = new URLSearchParams(); for (const [key, value] of Object.entries({ ...params, workspaceId, ...changes })) if (value != null && value !== "" && value !== "ALL") q.set(key, String(value)); return `/portfolio?${q}` }

export default async function PortfolioHome({ searchParams }: { searchParams: Promise<Params> }) {
	const params = await searchParams
	const session = await auth.api.getSession({ headers: await headers() })
	if (!session) return <div className="rounded-lg border bg-white p-8"><h1 className="text-lg font-semibold">Sign in required</h1><Link href="/login" className="mt-3 inline-block text-sm text-blue-700">Go to sign in →</Link></div>
	const { rows } = await authPool.query<Workspace>("select * from public.session_workspaces($1)", [session.session.token])
	const eligible = rows.filter(workspace => workspace.portfolio_enabled && workspace.cross_account_summary_enabled && workspace.can_view_portfolio)
	if (eligible.length === 0) return <div className="rounded-lg border bg-white p-8"><h1 className="text-lg font-semibold">Agency Portfolio is not available</h1><p className="mt-2 text-sm text-slate-600">This workspace does not have an active portfolio entitlement and view permission.</p><Link href="/" className="mt-3 inline-block text-sm text-blue-700">Open account dashboard →</Link></div>
	if (!params.workspaceId && eligible.length > 1) return <div className="space-y-4"><h1 className="text-xl font-semibold">Choose an Agency Portfolio</h1>{eligible.map(workspace => <Link key={workspace.workspace_id} href={`/portfolio?workspaceId=${encodeURIComponent(workspace.workspace_id)}`} className="block rounded-lg border bg-white p-4 font-medium text-blue-700 hover:bg-blue-50">{workspace.name}<span className="ml-2 text-xs font-normal text-slate-500">{workspace.role}</span></Link>)}</div>
	const workspace = eligible.find(value => value.workspace_id === params.workspaceId) ?? (!params.workspaceId && eligible.length === 1 ? eligible[0] : null)
	if (!workspace) return <div className="rounded-lg border border-red-200 bg-red-50 p-8"><h1 className="font-semibold text-red-800">Portfolio access denied</h1><p className="mt-2 text-sm text-red-700">The requested workspace is not authorized for this session.</p></div>
	const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1)
	const pageSize = [10, 50, 100].includes(Number(params.pageSize)) ? Number(params.pageSize) : 50
	const summary = await portfolioSummary(session.session.token, workspace.workspace_id, page, pageSize, workspace.portfolio_alerts_enabled)
	const attentionByTenant = new Map<string, number>()
	for (const item of summary.attention?.items ?? []) attentionByTenant.set(item.tenantId, (attentionByTenant.get(item.tenantId) ?? 0) + 1)
	const needle = (params.q ?? "").trim().toLowerCase()
	let accounts = summary.accounts.filter(account => (!needle || `${account.name} ${account.slug} ${account.marketplace ?? ""}`.toLowerCase().includes(needle)) && (!params.state || params.state === "ALL" || account.state === params.state))
	const sort = params.sort ?? "attention"
	accounts = [...accounts].sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "spend" ? (b.spend ?? -1) - (a.spend ?? -1) : sort === "sales" ? (b.sales ?? -1) - (a.sales ?? -1) : (attentionByTenant.get(b.tenantId) ?? 0) - (attentionByTenant.get(a.tenantId) ?? 0) || a.name.localeCompare(b.name))
	const totalPages = Math.max(1, Math.ceil(summary.total / pageSize))
	return <div className="space-y-8">
		<header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Agency Portfolio</p><h1 className="mt-1 text-2xl font-semibold">{workspace.name}</h1><p className="mt-1 text-sm text-slate-500">{summary.total} authorized accounts · {summary.coverage.withPerformanceData} with performance data</p></div>{eligible.length > 1 && <div className="flex flex-wrap gap-2">{eligible.map(value => <Link key={value.workspace_id} href={`/portfolio?workspaceId=${value.workspace_id}`} className={value.workspace_id === workspace.workspace_id ? "rounded bg-slate-900 px-3 py-2 text-xs text-white" : "rounded border bg-white px-3 py-2 text-xs text-slate-600"}>{value.name}</Link>)}</div>}</header>
		{summary.attention ? <section aria-labelledby="attention-heading"><div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><h2 id="attention-heading" className="text-sm font-semibold uppercase tracking-wide text-slate-500">Needs attention</h2><span className="text-xs text-slate-500">{summary.attention.counts.critical} critical · {summary.attention.counts.high} high · {summary.attention.counts.medium} medium</span></div>{summary.attention.items.length === 0 ? <p className="rounded-lg border bg-white p-4 text-sm text-slate-500">No current exceptions from available canonical sources.</p> : <div className="grid gap-3 lg:grid-cols-2">{summary.attention.items.slice(0, 12).map(item => <article key={`${item.tenantId}-${item.reason}`} className={`rounded-lg border p-4 ${severityTone(item.severity)}`}><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold">{item.severity} · {item.reason.replaceAll("_", " ")}</div><div className="mt-1 font-medium">{item.tenantName}</div><div className="mt-1 text-xs">Source: {item.sourceState}{item.count != null ? ` · ${item.count} items` : ""}</div></div>{workspace.can_operate_tenants && <PortfolioOpenAccount tenantId={item.tenantId} workspaceId={workspace.workspace_id} returnTo={item.drillDownRoute} />}</div></article>)}</div>}</section> : <section className="rounded-lg border border-slate-200 bg-slate-50 p-4"><h2 className="text-sm font-semibold">Attention feed unavailable</h2><p className="mt-1 text-xs text-slate-600">Portfolio alerts are not enabled for this workspace. Account summaries remain available.</p></section>}
		<section><h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Available aggregates by currency</h2>{summary.aggregates.length === 0 ? <p className="rounded-lg border bg-white p-4 text-sm text-slate-500">NO DATA — no compatible available metrics are included.</p> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.aggregates.map(value => <div key={value.currency} className="rounded-lg border bg-white p-4"><div className="text-xs uppercase tracking-wide text-slate-500">{value.currency} · {value.accountCount} accounts</div><div className="mt-2 text-xl font-semibold">{money(value.sales, value.currency)} sales</div><div className="mt-1 text-sm text-slate-600">{money(value.spend, value.currency)} spend · {percent(value.acos)} ACoS</div></div>)}</div>}</section>
		<section><form method="get" className="mb-4 grid gap-2 rounded-lg border bg-white p-3 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="workspaceId" value={workspace.workspace_id}/><label className="text-xs text-slate-500">Search<input name="q" defaultValue={params.q} placeholder="Client or marketplace" className="mt-1 w-full rounded border px-3 py-2 text-sm text-slate-900"/></label><label className="text-xs text-slate-500">Health<select name="state" defaultValue={params.state ?? "ALL"} className="mt-1 w-full rounded border px-3 py-2 text-sm text-slate-900"><option value="ALL">All states</option>{["AVAILABLE","NO_DATA","STALE","BLOCKED","WAITING_FOR_AUTHORIZATION","EXTERNAL_ACCESS_REQUIRED"].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-slate-500">Sort<select name="sort" defaultValue={sort} className="mt-1 w-full rounded border px-3 py-2 text-sm text-slate-900"><option value="attention">Needs attention</option><option value="name">Account name</option><option value="sales">Sales</option><option value="spend">Ad spend</option></select></label><label className="text-xs text-slate-500">Accounts per page<select name="pageSize" defaultValue={String(pageSize)} className="mt-1 w-full rounded border px-3 py-2 text-sm text-slate-900"><option>10</option><option>50</option><option>100</option></select></label><button className="self-end rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">Apply</button></form>
			<div className="space-y-3">{accounts.length === 0 ? <p className="rounded-lg border bg-white p-6 text-sm text-slate-500">No authorized accounts match these filters.</p> : accounts.map((account: AccountSummary) => <article key={account.tenantId} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{account.name}</h3><span className={`rounded px-2 py-1 text-[10px] font-semibold ${stateTone(account.state)}`}>{account.state}</span>{attentionByTenant.get(account.tenantId) ? <span className="rounded bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-800">{attentionByTenant.get(account.tenantId)} exceptions</span> : null}</div><p className="mt-1 text-xs text-slate-500">{account.marketplace ?? "Marketplace unavailable"} · {account.role} · data through {account.dataThrough ?? "—"}</p></div>{workspace.can_operate_tenants && <PortfolioOpenAccount tenantId={account.tenantId} workspaceId={workspace.workspace_id}/>}</div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4 lg:grid-cols-7"><Metric label="Sales" value={money(account.sales, account.currency)}/><Metric label="Ad spend" value={money(account.spend, account.currency)}/><Metric label="ACoS" value={percent(account.acos)}/><Metric label="Approvals" value={String(account.pendingApprovals)}/><Metric label="Alerts" value={String(account.openAlerts)}/><Metric label="Inventory" value={account.inventory.state}/><Metric label="Profit" value={account.contributionProfit.state}/></div></article>)}</div>
			<nav aria-label="Portfolio pagination" className="mt-4 flex items-center justify-between text-sm"><span>Page {page} of {totalPages}</span><div className="flex gap-2">{page > 1 && <Link href={href(workspace.workspace_id, params, { page: page - 1, pageSize })} className="rounded border bg-white px-3 py-2">Previous</Link>}{page < totalPages && <Link href={href(workspace.workspace_id, params, { page: page + 1, pageSize })} className="rounded border bg-white px-3 py-2">Next</Link>}</div></nav>
		</section>
	</div>
}

function Metric({ label, value }: { label: string; value: string }) { return <div><div className="text-xs uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 font-medium tabular-nums">{value}</div></div> }
