import { withTenant } from "@/lib/db"
import { money, percent } from "@/lib/format"
import { skuEconomics } from "@/lib/queries"
import { currentTenantId } from "@/lib/session"
export const dynamic = "force-dynamic"
export default async function Economics() {
	const tenantId = await currentTenantId()
	const rows = await withTenant(tenantId, c => skuEconomics(c))
	return <div className="space-y-4"><div><h1 className="text-lg font-semibold">SKU economics</h1><p className="text-sm text-slate-600">Cost ledger status, contribution margin and break-even ACOS.</p></div><div className="rounded border border-blue-200 bg-blue-50 p-3 text-sm"><b>Import or update costs:</b> copy <code>docs/cost-ledger-import.csv</code>, then run <code>python -m services.economics.cost_import your-file.csv --tenant-id {tenantId}</code> and <code>make dbt</code>. Browser writes remain disabled until authenticated upload and row-level validation are available.</div><div className="overflow-x-auto rounded border bg-white"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="p-3">SKU / ASIN</th><th className="p-3 num">Price</th><th className="p-3 num">COGS</th><th className="p-3 num">Unit cost</th><th className="p-3 num">Contribution</th><th className="p-3 num">Break-even ACOS</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r => <tr key={r.sku} className="border-b"><td className="p-3 font-medium">{r.sku}<div className="text-xs text-slate-500">{r.asin ?? "ASIN missing"}</div></td><td className="p-3 num">{money(r.avg_price)}</td><td className="p-3 num">{money(r.cogs)}</td><td className="p-3 num">{money(r.total_unit_cost)}</td><td className="p-3 num">{money(r.contribution_margin)}<div className="text-xs text-slate-500">{percent(r.contribution_margin_pct)}</div></td><td className="p-3 num">{percent(r.break_even_acos)}</td><td className={r.economics_incomplete ? "p-3 tone-warn" : "p-3 tone-good"}>{r.economics_incomplete ? "incomplete" : "ready"}</td></tr>)}</tbody></table></div></div>
}
