import { query, withTenant } from "@/lib/db"
import { stamp } from "@/lib/format"
import { currentContext } from "@/lib/session"
import { SettingsHeading } from "@/components/settings-ui"

type Audit={id:string;action:string;entity:string|null;actor_user_id:string|null;at:string;before:unknown;after:unknown}
function JsonBlock({ value }: { value: unknown }) { if (value === null || value === undefined) return <span className="text-slate-400">—</span>; return <pre className="max-h-48 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-50">{JSON.stringify(value, null, 2)}</pre> }

export default async function AuditSettingsPage({ searchParams }: { searchParams: Promise<{ action?: string; entity?: string }> }) {
	const actor=await currentContext(); const params=await searchParams; const action=(params.action ?? "").trim(); const entity=(params.entity ?? "").trim()
	const rows=await withTenant(actor.tenantId,c=>query<Audit>(c,"select id::text,action,entity,actor_user_id::text,at::text,before,after from audit_log where tenant_id=$1 and ($2='' or action ilike '%' || $2 || '%') and ($3='' or coalesce(entity,'') ilike '%' || $3 || '%') order by at desc limit 100",[actor.tenantId,action,entity]))
	return <div className="space-y-4"><SettingsHeading title="Audit logs" description="Recent tenant configuration and operator activity with before/after payloads."/><form className="grid gap-2 rounded border bg-white p-3 md:grid-cols-[1fr_1fr_auto]"><input name="action" defaultValue={action} placeholder="Filter action" className="rounded border px-3 py-2 text-sm"/><input name="entity" defaultValue={entity} placeholder="Filter entity" className="rounded border px-3 py-2 text-sm"/><button className="rounded bg-slate-900 px-4 py-2 text-sm text-white">Filter</button></form><div className="space-y-3">{rows.length?rows.map(row=><details key={row.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-medium">{row.action}</div><div className="text-xs text-slate-500">{row.entity??"—"}</div></div><div className="text-right text-xs text-slate-500"><div>{stamp(row.at)}</div><div className="font-mono">{row.actor_user_id??"system"}</div></div></div></summary><div className="mt-4 grid gap-3 md:grid-cols-2"><div><div className="mb-1 text-xs font-semibold uppercase text-slate-400">Before</div><JsonBlock value={row.before}/></div><div><div className="mb-1 text-xs font-semibold uppercase text-slate-400">After</div><JsonBlock value={row.after}/></div></div></details>):<div className="rounded-xl border bg-white p-8 text-center text-slate-500">No audit events recorded yet.</div>}</div></div>
}
